const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const path = require('path');
const ctx = vm.createContext({URL});
vm.runInContext(fs.readFileSync(path.join(__dirname, '../firefox-extension/filename-rules.js'), 'utf8'), ctx);
const rules = vm.runInContext('LensRules', ctx);
const old = {filenameRules:[{pattern:'*.pdf',folder:'D:\\PDF'}],routes:[{domain:'bank.example',folder:'D:\\Bank'}]};
assert.equal(rules.match(old,'report.pdf',{hostname:'bank.example'}).folder,'D:\\PDF');
assert.equal(rules.match(old,'file.zip',{hostname:'bank.example'}).folder,'D:\\Bank');
assert.equal(rules.match(old,'file.zip',{hostname:'chatgpt.com',conversation:'Hello'}).mode,'chatgpt');
const advanced = {...old, ruleOrder:['site-0','chatgpt','name-0']};
assert.equal(rules.match(advanced,'report.pdf',{hostname:'bank.example'}).folder,'D:\\Bank');
old.filenameRules[0].domain='bank.example';
assert.equal(rules.match(old,'report.pdf',{hostname:'other.example'}),null);
assert.equal(rules.match(old,'report.PDF',{hostname:'files.bank.example'}).folder,'D:\\PDF');
assert.equal(rules.match(old,'report.pdf',{hostname:'evilbank.example'}),null);
assert.equal(rules.expand('D:\\Files\\{domain}\\{year}\\{month}',{hostname:'bank.example',date:new Date(2026,8,13)}),'D:\\Files\\bank.example\\2026\\09');
assert.equal(rules.segment('CON'), '_CON');
for (const folder of ['D:\\..\\secret','relative','D:\\{unknown}','D:\\file:stream','D:\\x\u0000']) assert.equal(rules.validFolder(folder),false,folder);
const clean=rules.validate({...old,localDataConsent:{accepted:true},lastDestination:'secret',pendingCommand:'delete'});
assert.equal(clean.localDataConsent,undefined); assert.equal(clean.lastDestination,undefined);
assert.equal(clean.language,'auto'); assert.equal(clean.filenameRules[0].id,'name-0');
assert.throws(()=>rules.validate({...old,ruleOrder:['missing']}));
assert.throws(()=>rules.validate({...old,filenameRules:[{id:'chatgpt',pattern:'*',folder:'D:\\Files'}]}));
for (const url of ['blob:https://example.com/id','data:text/plain,secret','javascript:alert(1)','file:///C:/secret','https://user:pass@example.com']) assert.equal(rules.httpURL(url),'');
assert.equal(rules.eligibleURL('blob:https://example.com/id'),true);
assert.equal(rules.eligibleURL('data:text/plain,hello'),true);
assert.equal(rules.eligibleURL('file:///C:/secret'),false);
console.log('Advanced rules: legacy precedence, combined conditions, templates, import allowlist, path and URL guards PASS');
