const { chromium } = require('playwright');
const path = require('path');
const {pathToFileURL} = require('url');
const assert = require('assert');
(async () => {
  const browser = await chromium.launch({headless:true,channel:'msedge'});
  const page = await browser.newPage({viewport:{width:1100,height:1000}});
  const errors=[]; page.on('pageerror',e=>errors.push(String(e)));
  await page.addInitScript(() => {
    window.saved = {localDataConsent:{version:1,accepted:true},routes:[{domain:'example.com',folder:'D:\\Portal'}],filenameRules:[],language:'en'};
    window.browser = {
      i18n:{getUILanguage:()=> 'pl-PL'},
      storage:{local:{get:async defaults=>({...defaults,...window.saved}),set:async values=>Object.assign(window.saved,values)}},
      runtime:{getManifest:()=>({version:'1.2.0'}),sendNativeMessage:async()=>({ok:true,folder:'D:\\Chosen'})}
    };
  });
  await page.goto(pathToFileURL(path.resolve(__dirname,'../firefox-extension/options.html')).href);
  await page.getByRole('button',{name:'+ Add pattern'}).click();
  assert.equal(await page.locator('#aboutTitle').innerText(),'About the extension');
  assert.equal(await page.locator('.about-card').getAttribute('open'),null);
  await page.locator('#aboutTitle').click();
  assert.equal(await page.locator('.about-card #privacyLink').innerText(),'Privacy');
  assert.equal(await page.locator('#privacyLink').getAttribute('href'),'privacy.html');
  assert.match(await page.locator('.about-card .author').innerText(),/Arkadiusz Pajda.*Artllex.*2026/);
  assert.equal(await page.locator('.about-links a').count(),3);
  assert.equal(await page.locator('#previewName, #previewDomain, .preview-box').count(),0);
  assert.equal(await page.locator('#supportDownload').innerText(),'Download Windows installer');
  assert.match(await page.locator('#supportDownload').getAttribute('href'),/^https:\/\/github.com\/Artllex\/download-router\/releases\/download\/v1\.3\.3\/.*\.exe$/);
  assert.match(await page.locator('#supportDescription').innerText(),/Required/);
  let rows = page.locator('.name-rule');
  await rows.nth(0).locator('.domain').fill('*.zip');
  await rows.nth(0).locator('.folder').fill('D:\\Archives');
  await page.getByRole('button',{name:'+ Add pattern'}).click();
  await rows.nth(1).locator('.domain').fill('report*');
  await rows.nth(1).locator('.folder').fill('D:\\Games');
  await rows.nth(1).locator('.up').click();
  await rows.nth(0).locator('.enabled').uncheck();
  await rows.nth(0).locator('.enabled').check();
  await page.locator('#save').click();
  await page.locator('#chatgptFolder').fill('D:\\Chat files');
  await page.locator('#save').click();
  assert.equal(await page.evaluate(()=>saved.chatgptFolder),'D:\\Chat files');
  assert.equal((await page.evaluate(()=>saved.filenameRules))[0].pattern,'report*');
  assert.equal(await page.locator('#chatgptEnabled').isChecked(),true);
  await page.locator('#chatgptEnabled').uncheck();
  await page.locator('#save').click();
  assert.equal(await page.evaluate(()=>saved.chatgptEnabled),false);
  await page.evaluate(()=>restore());
  assert.equal(await page.locator('#chatgptEnabled').isChecked(),false);
  assert.equal((await page.evaluate(()=>saved.routes))[0].folder,'D:\\Portal');
  await page.locator('#language').selectOption('auto');
  assert.equal(await page.locator('#namesTitle').innerText(),'Reguły nazw plików');
  assert.equal(await page.locator('#privacyLink').innerText(),'Prywatność');
  assert.equal(await page.locator('#aboutTitle').innerText(),'O rozszerzeniu');
  assert.equal(await page.locator('#supportDownload').innerText(),'Pobierz instalator Windows');
  assert.equal(await page.locator('.advanced-card').getAttribute('open'),null);
  await page.locator('#advancedTitle').click();
  assert.equal(await page.locator('#priorityRules .priority-row').count(),4);
  await page.locator('#priorityRules .priority-row').last().getByRole('button',{name:'Przenieś wyżej'}).click();
  await page.locator('#save').click();
  assert.equal((await page.evaluate(()=>saved.ruleOrder)).length,4);
  await rows.nth(0).locator('.rule-advanced summary').click();
  await rows.nth(0).locator('.condition-domain').fill('bank.example');
  await page.locator('#save').click();
  assert.equal((await page.evaluate(()=>saved.filenameRules))[0].domain,'bank.example');
  const payload={format:'DownloadLens',version:1,settings:{routes:[],filenameRules:[{pattern:'*.pdf',folder:'D:\\Reports\\{year}',domain:'bank.example'}],language:'en',chatgptEnabled:true,chatgptFolder:'',localDataConsent:{accepted:false}}};
  await page.locator('#importFile').setInputFiles({name:'settings.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(payload))});
  await page.locator('#confirmImport').click();
  assert.equal((await page.evaluate(()=>saved.filenameRules)).length,2,'Import needs explicit Save');
  await page.locator('#save').click();
  assert.equal((await page.evaluate(()=>saved.filenameRules))[0].pattern,'*.pdf');
  assert.equal(await page.evaluate(()=>saved.localDataConsent.accepted),true);
  await page.locator('#importFile').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{broken')});
  assert.match(await page.locator('#backupStatus').innerText(),/Invalid/);
  assert.equal(await rows.nth(0).locator('.domain').inputValue(),'*.pdf');
  const downloadEvent=page.waitForEvent('download');
  await page.locator('#exportSettings').click();
  assert.equal((await downloadEvent).suggestedFilename(),'DownloadLens-settings.json');
  await page.screenshot({path:path.resolve(__dirname,'options-filename-rules.png'),fullPage:true});
  await page.setViewportSize({width:480,height:900});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('Options UI: add, reorder, enable, support link, save, preserve portals, PL/EN, narrow layout PASS');
})().catch(e=>{console.error(e);process.exit(1)});
